package p45;

import java.util.HashMap;

import res.Euler;

public class P45 extends Euler {
	
	public static void main(String[] args) {
		Euler p = new P45();
		System.out.println(p.description());
		System.out.println("\n------------------------------------------\n");
		System.out.println(p.run());
	}

	@Override
	public long run() {
		HashMap<Long, Long> heMap = new HashMap<Long, Long>();
		HashMap<Long, Long> peHeMap = new HashMap<Long, Long>();
		for(long h = 143; h < 100000; h++){
			long l = h*(2*h-1);
			heMap.put(l, l);
		}
		for(long p = 165; p < 100000; p++){
			long l = p*(3*p-1)/2;
			if(heMap.containsKey(l)){
				peHeMap.put(l, l);				
			}
		}
		for(long t = 286; t < 100000; t++){
			long l = t*(t+1)/2;
			if(peHeMap.containsKey(l)){
				return l;				
			}
		}
		
		return -1;
	}

	@Override
	public String getName() {
		return "P45";
	}

	@Override
	public String description() {
		return "Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:\n\n"
				+ "\tTriangle\tTn=n(n+1)/2\t1, 3, 6, 10, 15, ...\n"
				+ "\tPentagonal\tPn=n(3n−1)/2\t1, 5, 12, 22, 35, ...\n"
				+ "\tHexagonal\tHn=n(2n−1)\t1, 6, 15, 28, 45, ...\n\n"
				+ "It can be verified that T285 = P165 = H143 = 40755.\n\n"
				+ "Find the next triangle number that is also pentagonal and hexagonal.";
	}

}
